// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWniZ2Umpu2906-11BRgAMxKtHP7Bvc7Q',
    appId: '1:713307398084:web:c6c6a327a520ab2c848e91',
    messagingSenderId: '713307398084',
    projectId: 'pethaven-a2b04',
    authDomain: 'pethaven-a2b04.firebaseapp.com',
    storageBucket: 'pethaven-a2b04.firebasestorage.app',
    measurementId: 'G-8LEQKSY93G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGIsxGg131OWvavxy1CEymCjftXvHpmyE',
    appId: '1:713307398084:android:24d5b65752d5e4ae848e91',
    messagingSenderId: '713307398084',
    projectId: 'pethaven-a2b04',
    storageBucket: 'pethaven-a2b04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbzRVfHYGmUJ_RIp3tsjmRRkjldBKwQr0',
    appId: '1:713307398084:ios:3d228694775c168a848e91',
    messagingSenderId: '713307398084',
    projectId: 'pethaven-a2b04',
    storageBucket: 'pethaven-a2b04.firebasestorage.app',
    iosBundleId: 'com.example.pethaven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbzRVfHYGmUJ_RIp3tsjmRRkjldBKwQr0',
    appId: '1:713307398084:ios:3d228694775c168a848e91',
    messagingSenderId: '713307398084',
    projectId: 'pethaven-a2b04',
    storageBucket: 'pethaven-a2b04.firebasestorage.app',
    iosBundleId: 'com.example.pethaven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWniZ2Umpu2906-11BRgAMxKtHP7Bvc7Q',
    appId: '1:713307398084:web:f8b05d1da0997ab5848e91',
    messagingSenderId: '713307398084',
    projectId: 'pethaven-a2b04',
    authDomain: 'pethaven-a2b04.firebaseapp.com',
    storageBucket: 'pethaven-a2b04.firebasestorage.app',
    measurementId: 'G-X1K6VGR5LZ',
  );
}
